locale: uk
title: Late Summer Sale
description: >
  Now is the time to book your next getaway at the best price. We've got even bigger discounts on fantastic Med beach breaks, UK staycations, city breaks and far-flung sun! Awesome deals come and go, and dates sell out fast, so don't miss out - book before it's too late. Hurry, the SALE ends at 10 am on 5th August!

# value for cross site countdown timer
expires: 2024/08/05 10:00:00

# file paths
url: "https://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/uk/2024/late-summer-sale/" # the subpath of your site, e.g. /blog/
img: "/uk/2024/late-summer-sale/_assets/img"
css: "/uk/2024/late-summer-sale/_assets/css"
js: "/uk/2024/late-summer-sale/_assets/js"

exclude:
  [
    node_modules,
    package.json,
    package-lock.json,
    gulpfile.js,
    tailwind.config.js
  ]
keep_files: [_assets]
plugins:
  - jekyll-pages-directory
  - jekyll-liquify-alt
