locale: uk
title: Template
description: >
  Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

# value for cross site countdown timer
expires: 2050/01/01 12:00:00

# file paths
url: "https://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/_marketing/promo-template/uk" # the subpath of your site, e.g. /blog/
img: "/_marketing/promo-template/uk/_assets/img"
css: "/_marketing/promo-template/uk/_assets/css"
js: "/_marketing/promo-template/uk/_assets/js"

exclude:
  [
    node_modules,
    package.json,
    package-lock.json,
    gulpfile.js,
    tailwind.config.js
  ]
keep_files: [_assets]
plugins:
  - jekyll-pages-directory
  - jekyll-liquify-alt
