locale: de
title: Spätsommer-Sale
description: >
  Die beste Zeit zu buchen ist jetzt! Sichern Sie sich fantastische Rabatte auf Strandurlaube am Mittelmeer, Auszeiten in Ihrer Nähe, europäische Städtereisen und luxuriöse Fernreisen. Der Spätsommer-Sale endet am 5. August um 11 Uhr, also zögern Sie nicht lange und schnappen Sie sich Ihren Lieblings-Deal, bevor es zu spät ist!

# value for cross site countdown timer
expires: 2024/08/05 11:00:00

# file paths
url: "https://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/de/2024/sommer-sale" # the subpath of your site, e.g. /blog/
img: "/de/2024/sommer-sale/_assets/img"
css: "/de/2024/sommer-sale/_assets/css"
js: "/de/2024/sommer-sale/_assets/js"

exclude:
  [
    node_modules,
    package.json,
    package-lock.json,
    gulpfile.js,
    tailwind.config.js
  ]
keep_files: [_assets]
plugins:
  - jekyll-pages-directory
  - jekyll-liquify-alt
